# http://cvs.pld-linux.org/cgi-bin/viewvc.cgi/cvs/PLD-doc/uid_gid.db.txt

StandardUsers = [
	'root',
	'bin',
	'daemon',
	'adm',
	'lp',
	'sync',
	'shutdown',
	'halt',
	'mail',
	'news',
	'uucp',
	'operator',
	'games',
	'gopher',
	'ftp',
	'tftp',
	'syslog',
	'tvheadend',
	'nslcd',
	'rpc',
	'hlds',
	'sweep',
	'smmsp',
	'gnarwl',
	'jftpgw',
	'nscd',
	'radius',
	'pdns',
	'otrs',
	'dnslog',
	'dnscache',
	'tinydns',
	'pickdns',
	'walldns',
	'rbldns',
	'axfrdns',
	'ftplog',
	'sshd',
	'canna',
	'wnn',
	'clamav',
	'mksd',
	'intermezzo',
	'snort',
	'mldonkey',
	'parbuilder',
	'parbuilderd',
	'aspseek',
	'http',
	'cvs',
	'cvsadmin',
	'rsync',
	'xdm',
	'xfs',
	'icecast',
	'named',
	'darkice',
	'pop3',
	'opennap',
	'postfix',
	'courier',
	'ecartis',
	'aegis',
	'vpopmail',
	'listar',
	'pdns-recursor',
	'maasd',
	'ups',
	'sympa',
	'netsaint',
	'bb',
	'jabber',
	'ircd',
	'cyrus',
	'bs',
	'scanlogd',
	'exim',
	'amanda',
	'qmaild',
	'alias',
	'qmailq',
	'qmailr',
	'qmails',
	'qmaill',
	'qmailp',
	'postgres',
	'mysql',
	'saned',
	'squid',
	'pks',
	'slapd',
	'mailman',
	'dqs',
	'swserv',
	'amavis',
	'partimag',
	'nobody',
	'jboss',
	'sapdb',
	'dcc',
	'frox',
	'jftpgw',
	'backupc',
	'lire',
	'nullmail',
	'privoxy',
	'webCDwriter',
	'webwriter',
	'ifmail',
	'zabbix',
	'zope',
	'backups',
	'nagios',
	'gnunet',
	'lighttpd',
	'thttpd',
	'ffsearch',
	'wwwoffle',
	'ntop',
	'vpopmail',
	'messagebus',
	'stats',
	'quake3',
	'shishi',
	'haldaemon',
	'quagga',
	'cvsowner',
	'geneweb',
	'stunnel',
	'slony1',
	'tml',
	'log',
	'crontab',
	'safetp',
	'bacula',
	'distcc',
	'mysqlstat',
	'tss',
	'pdnsd',
	'captive',
	'bnc',
	'psybnc',
	'nscd',
	'firebird',
	'eventum',
	'smtpgw',
	'qtss',
	'mythtv',
	'imapproxy',
	'bopm',
	'newscache',
	'tuxaator',
	'jserv',
	'postgrey',
	'tor',
	'ogo',
	'munin',
	'natmonitor',
	'nx',
	'cherokee',
	'cancd',
	'vmail',
	'p0f',
	'avahi',
	'beagleindex',
	'ffserver',
	'gld',
	'hsqldb',
	'quake2',
	'hula',
	'dovecot',
	'logcheck',
	'rwhod',
	'tenshi',
	'sqlrelay',
	'motion',
	'wesnothd',
	'flixd',
	'svn',
	'srpms_builder',
	'builder',
	'ftpac',
	'cacti',
	'haproxy',
	'siets',
	'ais',
	'asterisk',
	'sequoia',
	'opendchub',
	'rpcstatd',
	'callwaver',
	'mysqlproxy',
	'zenoss',
	'vnstat',
	'unbound',
	'icecream',
	'flowd',
	'bfilter',
	'pound',
	'nexus',
	'gnump3d',
	'couchdb',
	'mpd',
	'gozerbot',
	'ganglia',
	'smokeping',
	'openctd',
	'memcached',
	'qscand',
	'ivman',
	'redmine',
	'nginx',
	'argus',
	'havp',
	'inspircd',
	'atheme',
	'anope',
	'vacation',
	'polkituser',
	'kojibuilder',
	'uuidd',
	'iscsi',
	'speech-dispatcher',
	'sabayon',
	'pulse',
	'flumotion',
	'splunk',
	'drizzle',
	'boinc',
	'pwrchute',
	'tomcat',
	'majordomo',
	'oracle',
	'arcabit',
	'ftpsync',
	'pgpool',
	'varnish',
	'davfs2',
	'red5',
	'glassfish',
	'hadoop',
	'ntp',
	'usbmux',
	'abrt',
	'sphinx',
	'murmur',
	'gammu-smsd',
	'kdm',
	'openerp-srv',
	'dovenull',
	'dkim-milter',
	'redis',
	'rabbitmq',
	'mongod',
	'cassandra',
	'radvd',
	'c-icap',
	'forked-daapd',
	'gitolite',
	'git',
	'ossec',
	'ossecm',
	'ossece',
	'ossecr',
	'rdnssd',
	'uwsgi',
	'bird',
	'grmilter',
	'tcpdump',
	'celery',
	'mpd_sima',
	'qemu',
	'rtkit',
	'sanlock',
	'bitlbee',
	'riak',
	'mfs',
	'polkitd',
	'minidlna',
	'snmptt',
	'systemd-journal-gateway',
	'elasticsearch',
	'carbon',
	'vagrant',
	'puppet',
	'mosquitto',
	'jenkins',
	'docker',
	'smtpd',
	'smtpq',
	'chef',
	'gnt-masterd',
	'gnt-confd',
	'gnt-luxid',
	'gnt-rapi',
	'prosody',
	'bes',
	'pcp',
	'pcpqa',
	'percona-toolkit',
	'xbm',
	'pesign',
	'fedmsg',
	'pathfinderd',
	'systemd-bus-proxy',
	'systemd-network',
	'systemd-resolve',
	'systemd-timesync',
	'systemd-journal-remote',
	'systemd-journal-upload',
	'naemon',
	'opendkim',
	'sddm',
	'nm-openvpn',
	'ddclient',
	'ftpauth',
	'diamond',
	'gearmand',
	'netdata',
	'gitlab-runner',
	'colord',
	'mopidy',
	'systemd-coredump',
	'hitch',
	'ftpcert',
	'vboxadd',
	'pykota',
]

StandardGroups = [
	'root',
	'bin',
	'daemon',
	'sys',
	'adm',
	'tty',
	'disk',
	'lp',
	'mem',
	'kmem',
	'wheel',
	'icmp',
	'mail',
	'news',
	'uucp',
	'man',
	'dialout/ttyS',
	'proc',
	'syslog',
	'floppy',
	'games',
	'slocate',
	'utmp',
	'audio',
	'video',
	'smmsp',
	'gnarwl',
	'cdrom/cdwrite',
	'fsctrl',
	'radius',
	'gopher',
	'console',
	'djbdns',
	'mldonkey',
	'lock',
	'jail',
	'hlds',
	'rlocate',
	'quake3',
	'backup',
	'dip',
	'canna',
	'wnn',
	'clamav',
	'mksd',
	'intermezzo',
	'snort',
	'mailq',
	'parbuilder',
	'parbuilderd',
	'ftp',
	'http',
	'cvs',
	'cvsadmin',
	'rsync',
	'xdm',
	'xfs',
	'icecast',
	'named',
	'tftp',
	'haclient',
	'opennap',
	'postfix',
	'maildrop',
	'ecartis',
	'aegis',
	'vchkpw',
	'listar',
	'tape',
	'maasd',
	'fonts',
	'sympa',
	'netsaint',
	'bb',
	'jabber',
	'ircd',
	'ups',
	'bs',
	'usb',
	'exim',
	'amanda',
	'nofiles',
	'qmail',
	'rbldns',
	'fuse',
	'darkice',
	'svn',
	'whois',
	'postgres',
	'mysql',
	'saned',
	'squid',
	'pks',
	'slapd',
	'mailman',
	'dqs',
	'swserv',
	'sweep',
	'partimag',
	'nobody',
	'jboss',
	'sapsys',
	'sysnews',
	'frox',
	'wireshark',
	'backupc',
	'lire',
	'nullmail',
	'privoxy',
	'lighttpd',
	'pkcs11',
	'zabbix',
	'zope',
	'backups',
	'nagios',
	'gnunet',
	'amavis',
	'crontab',
	'ffsearch',
	'wwwoffle',
	'ntop',
	'vchkpw',
	'messagebus',
	'stats',
	'logs',
	'shishi',
	'haldaemon',
	'quagga',
	'quaggavty',
	'geneweb',
	'stunnel',
	'thttpd',
	'tml',
	'log',
	'services',
	'digicam',
	'bacula',
	'distcc',
	'fileshare',
	'tss',
	'pdnsd',
	'captive',
	'bnc',
	'psybnc',
	'nscd',
	'firebird',
	'eventum',
	'nagcmd',
	'qtss',
	'mythtv',
	'imapproxy',
	'bopm',
	'newscache',
	'tuxaator',
	'jserv',
	'postgrey',
	'tor',
	'skyrix',
	'munin',
	'natmonitor',
	'kvm',
	'cherokee',
	'cancd',
	'vmail',
	'p0f',
	'avahi',
	'beagleindex',
	'ffserver',
	'gld',
	'hsqldb',
	'quake2',
	'hula',
	'dovecot',
	'logcheck',
	'rwhod',
	'tenshi',
	'sqlrelay',
	'motion',
	'wesnothd',
	'flixd',
	'kismet',
	'builder',
	'input',
	'xrdp',
	'dehydrated',
	'haproxy',
	'siets',
	'ais',
	'asterisk',
	'sequoia',
	'opendchub',
	'rpcstatd',
	'callwaver',
	'mysqlproxy',
	'zenoss',
	'vnstat',
	'mlocate',
	'icecream',
	'flowd',
	'bfilter',
	'pound',
	'nexus',
	'gnump3d',
	'couchdb',
	'mpd',
	'gozerbot',
	'ganglia',
	'smokeping',
	'mockbuild',
	'memcached',
	'qscand',
	'ivman',
	'ies4linux',
	'nginx',
	'argus',
	'havp',
	'inspircd',
	'atheme',
	'anope',
	'vacation',
	'polkituser',
	'vbox',
	'uuidd',
	'iscsi',
	'speech-dispatcher',
	'sabayon',
	'pulse',
	'pulse-rt',
	'pulse-access',
	'flumotion',
	'splunk',
	'drizzle',
	'boinc',
	'pwrchute',
	'tomcat',
	'majordomo',
	'dba',
	'servlet',
	'arcabit',
	'ftpsync',
	'pgpool',
	'varnish',
	'davfs2',
	'red5',
	'glassfish',
	'hadoop',
	'ntp',
	'usbmux',
	'abrt',
	'sphinx',
	'murmur',
	'gammu-smsd',
	'kdm',
	'openerp-srv',
	'dovenull',
	'dkim-milter',
	'redis',
	'rabbitmq',
	'mongod',
	'cassandra',
	'ecryptfs',
	'cgred',
	'c-icap',
	'forked-daapd',
	'gitolite',
	'git',
	'ossec',
	'vboxsf',
	'rdnssd',
	'uwsgi',
	'bird',
	'grmilter',
	'lxd',
	'celery',
	'mpd_sima',
	'qemu',
	'sslh',
	'rtkit',
	'sanlock',
	'bitlbee',
	'riak',
	'mfs',
	'polkitd',
	'minidlna',
	'snmptt',
	'shadow',
	'systemd-journal-gateway',
	'systemd-journal',
	'elasticsearch',
	'carbon',
	'vagrant',
	'puppet',
	'mosquitto',
	'rspamd',
	'jenkins',
	'docker',
	'smtpd',
	'smtpq',
	'chef',
	'gnt-masterd',
	'gnt-confd',
	'gnt-luxid',
	'gnt-rapi',
	'gnt-daemons',
	'gnt-admin',
	'prosody',
	'bes',
	'pcp',
	'pcpqa',
	'percona-toolkit',
	'xbm',
	'pesign',
	'fedmsg',
	'pathfinderd',
	'systemd-bus-proxy',
	'systemd-network',
	'systemd-resolve',
	'systemd-timesync',
	'systemd-journal-remote',
	'systemd-journal-upload',
	'naemon',
	'opendkim',
	'sddm',
	'nm-openvpn',
	'ddclient',
	'ftpauth',
	'diamond',
	'gearmand',
	'netdata',
	'gitlab-runner',
	'colord',
	'mopidy',
	'systemd-coredump',
	'hitch',
	'ftpcert',
	'pykota',
	'users',
	'tpexec',
	'nosock',
	'nocsock',
	'nossock',
]
